name: Build and Release APK

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the release (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
        type: string
      create_release:
        description: 'Create a GitHub release'
        required: false
        default: true
        type: boolean

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Get release info
      id: release_info
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "release_name=Release ${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "tag_name=${{ inputs.version }}" >> $GITHUB_OUTPUT
          echo "release_name=Release ${{ inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "tag_name=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          echo "release_name=${{ github.event.release.name }}" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.create_release)
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.release_info.outputs.tag_name }}
        name: ${{ steps.release_info.outputs.release_name }}
        draft: false
        prerelease: false
        body: |
          ## GPS Android App - ${{ steps.release_info.outputs.tag_name }}

          ### APK Files
          - `app-debug.apk` - Debug version for development and testing
          - `app-release-unsigned.apk` - Release version (unsigned)

          ### Installation
          Download the appropriate APK file and install it on your Android device.

          **Note**: You may need to enable "Install from unknown sources" in your device settings.

    - name: Upload Release Assets
      if: github.event_name == 'push' || github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.create_release)
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.release_info.outputs.tag_name }}
        files: |
          ./app/build/outputs/apk/debug/app-debug.apk
          ./app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Upload APKs as Artifacts (Manual Dispatch)
      if: github.event_name == 'workflow_dispatch' && !inputs.create_release
      uses: actions/upload-artifact@v4
      with:
        name: apk-files-${{ steps.release_info.outputs.tag_name }}
        path: |
          ./app/build/outputs/apk/debug/app-debug.apk
          ./app/build/outputs/apk/release/app-release-unsigned.apk